apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elm-css-modules-plugin
  description: |
    Elm CSS Modules Plugin
  tags:
    - camp-developer-experience
    - data-none
    - users-na
  annotations:
    github.com/project-slug: cultureamp/elm-css-modules-plugin
    github.com/team-slug: cultureamp/delivery-engineering
spec:
  type: library
  owner: delivery-engineering
  lifecycle: production
